---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-bootstrap
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openbao-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: openbao-ca
  secretName: openbao-ca
  duration: 87600h     # 10 years
  renewBefore: 720h    # 30 days
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-bootstrap
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: openbao-ca-issuer
spec:
  ca:
    secretName: openbao-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openbao-server-tls
  namespace: openbao
spec:
  secretName: openbao-server-tls
  duration: 2160h      # 90 days
  renewBefore: 720h    # 30 days
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  commonName: openbao
  dnsNames:
    - openbao
    - openbao.openbao
    - openbao.openbao.svc
    - openbao.openbao.svc.cluster.local
    - openbao-internal
    - openbao-internal.openbao
    - openbao-internal.openbao.svc
    - openbao-internal.openbao.svc.cluster.local
    - openbao-0.openbao-internal
    - openbao-1.openbao-internal
    - openbao-2.openbao-internal
    - openbao-0.openbao-internal.openbao.svc.cluster.local
    - openbao-1.openbao-internal.openbao.svc.cluster.local
    - openbao-2.openbao-internal.openbao.svc.cluster.local
    - openbao.securek8s.de
    - localhost
  ipAddresses:
    - 127.0.0.1
  issuerRef:
    name: openbao-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
